version: '2'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      SAMPLE_APP_DB_HOST: postgres
      SAMPLE_APP_DB_USER: user
      SAMPLE_APP_DB_PASSWORD: password
      SAMPLE_APP_DB_NAME: app_database
      SAMPLE_APP_TEST_DB_NANE: app_test_database

  postgres:
    image: postgres:9.5.2
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_APP_DB: app_database
      POSTGRES_APP_TEST_DB: app_test_database

volumes:
  db_data:
    driver: local
  bundle_data:
    driver: local
